[env]
RUST_MIN_STACK = "4194304"

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[alias]
build-all = "build --all --exclude zydeco-runtime"
test-all = "test --all --exclude zydeco-runtime"
clippy-all = "clippy --all --exclude zydeco-runtime"
clippy-fix-all = "clippy --all --exclude zydeco-runtime --fix"
